# Generated by Django 4.2.2 on 2023-06-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_order_customer_cart_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
