# Generated by Django 4.2.2 on 2023-07-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_cart_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(null=True, upload_to='product_photos'),
        ),
    ]
